### ISSUE TITLE
Start menu pops up randomly

### ISSUE THREAD

**Issue by jneisener** [GruberMarkus/Surface-Pen-PowerPoint-Clicker#2]
The script works fine, most of the time... But sometimes the start menu pops up, apparently after a random amout of pen-button presses.

I have looked around for solutions online and the only mention I found was in [this](https://www.reddit.com/r/Surface/comments/6uuour/ahk_powerpoint_presentation_script_start_menu/) reddit thread, where no solution was provided.

I don't know where else to ask, do you have any idea why this happens?

**Comment by alessandrozoppi** [comment]
@johenning I had the same problem, with the start menu showing up randomly. [Here](http://www.surfaceforums.net/threads/sp3-pen-to-control-powerpoint-presentation.11660/) I found a similar thread but with a slightly different AutoHotKey script that apparently solves the issue.

**Comment by jneisener** [comment]
@alessandrozoppi Thank you. I looked at the differences: Turns out using `PgUp` and `PgDn` instead of `left` and `right` fixes this problem.

**Comment by GruberMarkus** [comment]
Personally, I never experienced this start menu issue. Can you confirm that using PgUp/PdWn instead of left/right solves the issue?

Is the issue reproducable?
